services:
  billion-db:
    image: mysql:8.0
    container_name: billion-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - billion-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  billion-app:
    build:
      context: ./
      target: dev
    container_name: billion-app
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    networks:
      - billion-net

  billion-redis:
    image: redis:7.4.2-alpine
    container_name: billion-cache
    restart: always
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --save ""
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USERNAME}
      REDIS_USER_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - billion-net

networks:
  billion-net:
    driver: 'bridge'

volumes:
  db-data: